POST localhost:8000/api/v1/login
Content-Type: application/json

{
  "username": "Ross",
  "password": "pass123"
}

###
POST localhost:8000/api/v1/signup
Content-Type: application/json

{
  "username": "Ross",
  "confirmUsername": "Ross",
  "password": "pass123",
  "confirmPassword": "asd"
}

###
POST localhost:8000/api/v1/chats
Content-Type: application/json

{
  "username": "Ross"
}