
# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Develop CI

on:
  push:
    branches: [ ross ]
  pull_request:
    branches: [ ross ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Define version'
        required: true
        default: 'latest'


jobs:
  build_push_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login --username rossmaclean --password ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build -t rossmaclean/cryptchat:${{ github.event.inputs.version }} .
      - run: docker push rossmaclean/cryptchat:${{ github.event.inputs.version }}

  deploy_test:
    needs: build_push_image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: npm i -g cloudron
      - run: cloudron update --server my.rossmac.co.uk --token ${{ secrets.CLOUDRON_TOKEN }} --app cryptchat.test.rossmac.co.uk --image rossmaclean/cryptchat:${{ github.event.inputs.version }}
