# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build__push_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login --username rossmaclean --password ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build -t rossmaclean/cryptchat:$GITHUB_RUN_ID .
      - run: docker push rossmaclean/cryptchat:$GITHUB_RUN_ID
